global:
  resolve_timeout: 5m
  slack_api_url: ""

route:
  receiver: slack_alerts
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
- name: slack_alerts
  slack_configs:
    - channel: "#hemlock"
      send_resolved: true
      title: "{{ .CommonLabels.alertname }}"
      text: |
        *Alert:* {{ .CommonLabels.alertname }}
        *Severity:* {{ .CommonLabels.severity }}
        *Instance:* {{ .CommonLabels.instance }}
        {{ range .Alerts -}}
        *Description:* {{ .Annotations.description }}
        {{ end }}


      