services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "8883:8883"
    expose:
      - "1883" 
    volumes:
      - ./mosquitto:/mosquitto

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb2:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=river_org
      - DOCKER_INFLUXDB_INIT_BUCKET=river_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mysecrettoken

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
      - mosquitto
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./mosquitto/certs/ca.crt:/etc/telegraf/ca.crt:ro
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana

  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"     # HTTP API / UI
      - "8600:8600/udp" # DNS
    command: agent -dev -client=0.0.0.0
    volumes:
      - consul-data:/consul/data

  mqtt-register:
    image: curlimages/curl:latest
    container_name: mqtt-register
    depends_on:
      - mosquitto
      - consul
    volumes:
      - ./consul:/consul
    entrypoint: >
      sh -c "
      curl --request PUT --data @/consul/mosquitto-consul.json http://consul:8500/v1/agent/service/register
      "
    restart: "no"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    restart: unless-stopped

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    ports:
      - "9093:9093"
  
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

  mosquitto-exporter:
    image: jryberg/mosquitto-exporter:v0.7.7
    platform: linux/arm64
    container_name: mosquitto-exporter
    ports:
      - "9234:9234"
    environment:
      - BROKER_ENDPOINT=tcp://mosquitto:1883
      - MQTT_USER=scraper
      - MQTT_PASS=telemetrics
    restart: unless-stopped
    depends_on:
      - mosquitto

volumes:
  influxdb2:
  grafana_data:
  consul-data:
